from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from src.api.models.common_models import RequestMixin


class SuiteAttributesRelaxed(RequestMixin):
    # We use Any | None to allow any data type during negative tests
    suite_id: Any | None = Field(default=None, alias="suite-id")

    # Notice we don't use default_factory=list here because for
    # a relaxed model, we want the default to be 'missing' (None)
    children: Any | None = None
    code: Any | None = None
    comments_count: Any | None = None
    created_at: Any | None = Field(default=None, alias="created-at")
    description: Any | None = Field(default=None, alias="description")
    file: Any | None = None
    file_type: Any | None = Field(default=None, alias="file-type")
    fullpath: Any | None = None
    tags: Any | None = None
    test_count: Any | None = Field(default=None, alias="test-count")
    tests: Any | None = None
    title: Any | None = None
    to_url: Any | None = Field(default=None, alias="to_url")
    updated_at: Any | None = Field(default=None, alias="updated-at")


class SuiteBodyPropsRelaxed(RequestMixin):
    id: Any | None = None
    type: Any | None = None
    attributes: Any | None = None
    relationships: Any | None = None


class SuiteAttributesStrict(BaseModel):
    # Mandatory fields (must be in JSON)
    suite_id: str | None = Field(default=None, alias="suite-id")  # is autogenerated

    # Optional fields (using the pipe | operator)
    children: list[str] = Field(default_factory=list)
    code: str | None = None
    comments_count: float | None = None
    created_at: str | None = Field(None, alias="created-at")
    description: str | None = Field(None, alias="description")
    file: str | None = None
    file_type: str | None = Field(None, alias="file-type")
    fullpath: str | None = None
    tags: list[str] = Field(default_factory=list)
    test_count: float | None = Field(None, alias="test-count")
    tests: list[str] = Field(default_factory=list)
    title: str | None = None
    to_url: str | None = Field(None, alias="to_url")
    updated_at: str | None = Field(None, alias="updated-at")


class SuiteBodyPropsStrict(BaseModel):
    id: str = Field(...)
    type: Literal["suite"] = Field(...)
    attributes: SuiteAttributesStrict
    relationships: dict[str, Any]
